<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Indexed.Abstractions</AssemblyName>
        <RootNamespace>Indexed.Abstractions</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Indexed.Targets/Indexed.Targets.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Indexed.Abstractions.Tests" />
    </ItemGroup>
</Project>
