<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Indexed.Extractors</AssemblyName>
        <RootNamespace>Indexed.Extractors</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Indexed.Abstractions/Indexed.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    </ItemGroup>
</Project>
